### ISSUE TITLE
Add missing HDcube models

### ISSUE THREAD

**Issue by RunDevelopment** [OpenModelDB/open-model-database#127]
Add all HDCube models. Their license is kinda weird though:

> You may not rent, sell or **redistribute** the generative model or any portion thereof without permission.

(Highlighting by me)

This prevents us from hosting the model ourselves or creating any mirrors.

https://github.com/Venomalia/HDcube

**Comment by joeyballentine** [comment]
We can still list it though right?

**Comment by RunDevelopment** [comment]
Maybe. I found out about the licensing situation of those models and that v4 is commercial after I made this issue. I made an issue for this https://github.com/Venomalia/HDcube/issues/1, so let's wait and see.

**Comment by RunDevelopment** [comment]
I got a response. v2 and v2 compact have permissive licenses, so we can add them no problem.

**Comment by RunDevelopment** [comment]
v2 samples: https://imgsli.com/MTM5ODE0/0/2
