### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by ferrosa** [OpenModelDB/open-model-database#276]
Even with such a new technology, models quickly become superseeded and improved versions are uploaded.
Hence it's useful to check which of several similarly named models is newer.
I'd kindly request a "date" or "newest/oldest" entry in the sort dropdown menu.
![Screenshot from 2023-09-11 17-47-13](https://github.com/OpenModelDB/open-model-database/assets/20930937/21dfcd4c-910d-4e34-8330-eb0d4cf90245)

**Comment by joeyballentine** [comment]
Try sorting by "latest"

**Comment by ferrosa** [comment]
Oh dear, someone is very blind.
Thanks.
