### ISSUE TITLE
How do i use the "compact" models ?

### ISSUE THREAD

**Issue by Ulf3000** [OpenModelDB/open-model-database#279]
neither a1111 nor cupscale can use these models. how to use ? 

example model:
https://openmodeldb.info/models/1x-AnimeUndeint-Compact

**Comment by RunDevelopment** [comment]
You can use [chaiNNer](https://github.com/chaiNNer-org/chaiNNer#chainner). It's not as easy to use as a1111 or CupScale, but it's more powerful in return. You can [download chaiNNer here](https://chainner.app/download). [Here's a quick tutorial](https://www.youtube.com/watch?v=-8N2dXuRnK4) on how to use it.

**Comment by Ulf3000** [comment]
is there a way to convert them instead to a compatible ersgan format?

**Comment by joeyballentine** [comment]
No, they're different architectures. You can't just convert it to an esrgan model
