### ISSUE TITLE
I want to ask some questions about model training.

### ISSUE THREAD

**Issue by sanbuphy** [OpenModelDB/open-model-database#329]
Hello, thank you very much for your great work! I also want to start training my own super-resolution model. I would like to ask how many high-quality images are needed to train a good model (such as esrgan)? And what kind of graphics card is needed for how long (I have a 3060, may need to rent a 3090)? Is there any recommended training script? Thank you.

**Comment by joeyballentine** [comment]
You can definitely train on a 3060, especially if it's a 12gb variant (I train on an 8gb card). [NeoSR](https://github.com/muslll/neosr) is what we'd recommend for training new models. How big of a dataset is kinda up to how large and how good all the images are. I think in the neosr documentation it gives some recommendations. As for how long, that also depends on a lot of things, but I can say from personal experience it sometimes takes 2-3 days. But really itll just take as long as it takes to get a good result.

**Comment by sanbuphy** [comment]
> You can definitely train on a 3060, especially if it's a 12gb variant (I train on an 8gb card). [NeoSR](https://github.com/muslll/neosr) is what we'd recommend for training new models. How big of a dataset is kinda up to how large and how good all the images are. I think in the neosr documentation it gives some recommendations. As for how long, that also depends on a lot of things, but I can say from personal experience it sometimes takes 2-3 days. But really itll just take as long as it takes to get a good result.

Thank you for your thoughtful response! This is really great, and I will definitely give it a try. Thank you all for your support!
