### ISSUE TITLE
Prevent lag in search page

### ISSUE THREAD

**Issue by RunDevelopment** [OpenModelDB/open-model-database#58]
When changing tag selection from some tag with few models to no selection (meaning all models are selected), the search page lags, because it has to render cards for all models. The issue here isn't React. Adding that many DOM elements just takes some time.

Find a way to prevent this lag.

There are multiple ways this could be done. Some ideas:
- Pagination.
- Infinite scroll. Display more cards as the user scrolls.
- Spread out adding cards over multiple ticks. So for some tick rate (e.g. 20Hz), render N cards on tick 1, then 2\*N cards in tick 2, 3\*N cards in tick 3, and so on until all cards are rendered.

**Comment by joeyballentine** [comment]
I don't think pagination makes much sense when we aren't needing to fetch live data. I'd prefer an infinite scroll or the tick thing personally

**Comment by RunDevelopment** [comment]
Same. Ideally, we could connect the infinite scroll or other solutions with lazily loading card images. We should only load card images that the user can see.
